#端口号
server:
  port: 8081
spring:
  application:
    #指定应用名称
    name: reggie_take_out
  datasource:
#    数据源
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: lujiahao

#mail:
#  host: smtp.qq.com
#    # 你的QQ邮箱，这里为发件人，填自己的即可
#    username: 997447204@qq.com
#    # 你的QQ邮箱授权码
#    password: hxgjhdlabosgbega
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: E:\bbbxiao\